### ISSUE TITLE
APM agent not sending event requests to the APM server with gunicorn wsgi.

### ISSUE THREAD

**Issue by umarriqbal** [elastic/apm-agent-python#624]
I'm running a flask application and everything works fine if I'm running the application in dev environment i.e. directly from command line or my IDE aka Pycharm.

But when I run the same app on production via gunicorn, it only sends `agents` requests and no `events` requests so in APM in kibana, no service shows up.

**Reproduction steps:**
1. Create a basic flask app and call `client.begin_transaction` and `client.end_transaction` before and after each request so as to log time of each request.
2. Run the app via `gunicorn`.
3. Make a request to the app via browser or postman.

**Expected behavior**: 

The apm server logs show `/intake/v2/events` requests as well as `/config/v1/agents` request.

**Environment/**
- OS: macOS
- Python version: 3.5
- Framework and version: Flask 1.0.2 
- Elasticsearch version: 7.4.1
- Kibana version: 7.4.1
- APM Server version: 7.4.1
- Agent version: 5.2.2

**Additional context**

I'm running Elasticsearch on 0.0.0.0:9200, Kibana on 0.0.0.0:5601, and APM on 0.0.0.0.8200.

A `curl` request to all these shows the desired result.

**Comment by basepi** [comment]
Thanks for the report! I'm going to find some time to try to reproduce this, and I'll follow up later this week.

**Comment by nabilm** [comment]
Hey @basepi , any workaround for this issue? currently, we are blocked from using elastic APM because of that issue 
but I'm having this issue with Django ran by gunicorn Django elastic agent test command report that everything is fine but no Django events reported .. ( like requests for instance), however, celery tasks are reported well but when it comes to Django no

**Comment by nabilm** [comment]
Okay, i made it work with gunicorn by disabling preload_apps   ( preload_app = False ) in gunicorn config

**Comment by basepi** [comment]
Ah, interesting! Glad you got it working, @nabilm.

@umarriqbal would you mind trying `preload_app = False` in your gunicorn config and see if that fixes your issue as well?

**Comment by basepi** [comment]
This may also be fixed by #636 once it's merged. I have a feeling that if it's not the `preload_app = False`, then it's probably an issue with forking after creating the background worker threads, which results in them being lost and never sending the traces. #636 should fix that.

**Comment by MaiSuiYuMi** [comment]
Hey @basepi ,I also find this issue,my app run in uwsgi.

**Comment by basepi** [comment]
Hello @MaiSuiYuMi ! Have you had a chance to try `preload_app = False`? That seemed to help [others](https://github.com/elastic/apm-agent-python/issues/624#issuecomment-558136833). Otherwise #636 should fix this issue once it's complete. Sorry for the inconvenience!

**Comment by Kalanamith** [comment]
We are facing the same issue as well , making `preload_app = False` didnt make any difference. This is not a gunicorn specific issue,This issue persists in uwsgi and gevent as well

**Comment by basepi** [comment]
Thanks for the update. Forking models for concurrency have long given the agent issues, as we lose the background threads on fork. Rather than trying to come up with a solution for each implementation, we're going to focus on #636 so that we will automatically detect forks and re-create those background threads. This should fix the majority of issues like this one.

**Comment by wodCZ** [comment]
I can confirm that disabling preloading in gunicorn fixes the issue - transactions are now properly saved.

We're using this docker CMD with no configuration file:
```
CMD ["gunicorn", "--bind", ":8000", "--worker-tmp-dir", "/dev/shm/", "--workers", "2", "--threads", "4", "--worker-class", "eventlet", "--log-file", "-", "project.wsgi"]
```

I also had to switch the transaction type to `request` in the APM UI:
![image](https://user-images.githubusercontent.com/1174421/72350938-a742c800-36df-11ea-9667-7c9143438130.png)

**Comment by beniwohli** [comment]
We just released a new version of the agent that should fix this issue, can y'all try to install 5.4.1 and see if the problem goes away, even with preloading?

I'll close this issue for now, please re-open it if you still encounter the bug.
